{{- if .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "raggo.componentName" (dict "ctx" $ "component" "frontend") }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "raggo.componentLabels" (dict "ctx" $ "component" "frontend") | nindent 4 }}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.frontend.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.frontend.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.frontend.ingress.path | quote }}
            pathType: {{ .Values.frontend.ingress.pathType | quote }}
            backend:
              service:
                name: {{ include "raggo.componentName" (dict "ctx" $ "component" "frontend") }}
                port:
                  number: {{ .Values.frontend.service.port }}
  {{- with .Values.frontend.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
