import { useEffect, useState } from "react";
import { api, Stats, Health, IngestResponse } from "../api";

function StatCard({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="stat">
      <div className="stat-label">{label}</div>
      <div className="stat-value">{value}</div>
    </div>
  );
}

export default function Dashboard() {
  const [stats, setStats] = useState<Stats | null>(null);
  const [health, setHealth] = useState<Health | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [ingesting, setIngesting] = useState(false);
  const [ingestResult, setIngestResult] = useState<IngestResponse | null>(null);

  async function refresh() {
    setError(null);
    try {
      const [s, h] = await Promise.all([api.stats(), api.health()]);
      setStats(s);
      setHealth(h);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }

  useEffect(() => {
    void refresh();
    const id = setInterval(refresh, 10_000);
    return () => clearInterval(id);
  }, []);

  async function runIngest() {
    setIngesting(true);
    setIngestResult(null);
    setError(null);
    try {
      const result = await api.ingest();
      setIngestResult(result);
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setIngesting(false);
    }
  }

  return (
    <>
      <h1>Dashboard</h1>
      {error && <div className="error">{error}</div>}

      <div className="card">
        <div className="muted" style={{ marginBottom: 8 }}>
          Backend status
        </div>
        <div>
          API:{" "}
          <span className={health?.status === "ok" ? "severity-info" : "severity-critical"}>
            {health?.status ?? "…"}
          </span>{" "}
          · Database:{" "}
          <span className={health?.database === "ok" ? "severity-info" : "severity-critical"}>
            {health?.database ?? "…"}
          </span>
        </div>
      </div>

      <h2>Counts</h2>
      <div className="stat-grid">
        <StatCard label="Flights" value={stats?.flights ?? "…"} />
        <StatCard label="Flight logs" value={stats?.flight_logs ?? "…"} />
        <StatCard label="Incidents" value={stats?.incidents ?? "…"} />
        <StatCard label="Embedded logs" value={stats?.embedded_logs ?? "…"} />
        <StatCard label="Unembedded logs" value={stats?.unembedded_logs ?? "…"} />
      </div>

      <h2>Ingestion</h2>
      <div className="card">
        <div className="muted" style={{ marginBottom: 10 }}>
          Triggers a bounded ingestion pass on the backend. Embeddings are
          generated by the local embedding model — the frontend never calls it
          directly.
        </div>
        <button onClick={runIngest} disabled={ingesting}>
          {ingesting ? "Running…" : "Run ingestion pass"}
        </button>
        {ingestResult && (
          <div className="notice" style={{ marginTop: 10 }}>
            Scanned {ingestResult.scanned}, embedded {ingestResult.embedded}
            {ingestResult.errors.length > 0
              ? `, errors: ${ingestResult.errors.length}`
              : ""}
            .
          </div>
        )}
      </div>
    </>
  );
}
